
INSERT INTO book_images (file_id, book_id, book_image_type) values
                                                                (1,1, "DETAIL"),
                                                                (2,2, "DETAIL"),
                                                                (3,3, "DETAIL"),
                                                                (4,4, "DETAIL"),
                                                                (5,5, "DETAIL"),
                                                                (6,6, "DETAIL"),
                                                                (7,7, "DETAIL"),
                                                                (8,8, "DETAIL"),
                                                                (9,9, "DETAIL"),
                                                                (10,10,"DETAIL"),
                                                                (11,11,"DETAIL"),
                                                                (12,12,"DETAIL"),
                                                                (13,13,"DETAIL"),
                                                                (14,14,"DETAIL"),
                                                                (15,15,"DETAIL"),
                                                                (16,16,"DETAIL"),
                                                                (17,17,"DETAIL"),
                                                                (18,18,"DETAIL"),
                                                                (19,19,"DETAIL"),
                                                                (20,20,"DETAIL"),
                                                                (21,21,"DETAIL"),
                                                                (22,22,"DETAIL"),
                                                                (23,23,"DETAIL"),
                                                                (24,24,"DETAIL"),
                                                                (25,25,"DETAIL"),
                                                                (26,26,"DETAIL"),
                                                                (27,27,"DETAIL"),
                                                                (28,28,"DETAIL"),
                                                                (29,29,"DETAIL"),
                                                                (30,30,"DETAIL"),
                                                                (31,31,"DETAIL"),
                                                                (32,32,"DETAIL"),
                                                                (33,33,"DETAIL"),
                                                                (34,34,"DETAIL"),
                                                                (35,35,"DETAIL"),
                                                                (36,36,"DETAIL"),
                                                                (37,37,"DETAIL"),
                                                                (38,38,"DETAIL"),
                                                                (39,39,"DETAIL"),
                                                                (40,40,"DETAIL"),
                                                                (41,41,"DETAIL"),
                                                                (42,42,"DETAIL"),
                                                                (43,43,"DETAIL"),
                                                                (44,44,"DETAIL"),
                                                                (45,45,"DETAIL"),
                                                                (46,46,"DETAIL"),
                                                                (47,47,"DETAIL"),
                                                                (48,48,"DETAIL"),
                                                                (49,49,"DETAIL"),
                                                                (50,50,"DETAIL"),
                                                                (51,51, "DETAIL"),
                                                                (52,52, "DETAIL"),
                                                                (53,53, "DETAIL"),
                                                                (54,54, "DETAIL"),
                                                                (55,55, "DETAIL"),
                                                                (56,56, "DETAIL"),
                                                                (57,57, "DETAIL"),
                                                                (58,58, "DETAIL"),
                                                                (59,59, "DETAIL"),
                                                                (60,60,"DETAIL"),
                                                                (61,61,"DETAIL"),
                                                                (62,62,"DETAIL"),
                                                                (63,63,"DETAIL"),
                                                                (64,64,"DETAIL"),
                                                                (65,65,"DETAIL"),
                                                                (66,66,"DETAIL"),
                                                                (67,67,"DETAIL"),
                                                                (68,68,"DETAIL"),
                                                                (69,69,"DETAIL"),
                                                                (70,70,"DETAIL"),
                                                                (71,71,"DETAIL"),
                                                                (72,72,"DETAIL"),
                                                                (73,73,"DETAIL"),
                                                                (74,74,"DETAIL"),
                                                                (75,75,"DETAIL"),
                                                                (76,76,"DETAIL"),
                                                                (77,77,"DETAIL"),
                                                                (78,78,"DETAIL"),
                                                                (79,79,"DETAIL"),
                                                                (80,80,"DETAIL"),
                                                                (81,81,"DETAIL"),
                                                                (82,82,"DETAIL"),
                                                                (83,83,"DETAIL"),
                                                                (84,84,"DETAIL"),
                                                                (85,85,"DETAIL"),
                                                                (86,86,"DETAIL"),
                                                                (87,87,"DETAIL"),
                                                                (88,88,"DETAIL"),
                                                                (89,89,"DETAIL"),
                                                                (90,90,"DETAIL"),
                                                                (91,91,"DETAIL"),
                                                                (92,92,"DETAIL"),
                                                                (93,93,"DETAIL"),
                                                                (94,94,"DETAIL"),
                                                                (95,95,"DETAIL"),
                                                                (96,96,"DETAIL"),
                                                                (97,97,"DETAIL"),
                                                                (98,98,"DETAIL"),
                                                                (99,99,"DETAIL"),
                                                                (100,100,"DETAIL");
