SET sql_safe_updates=0;
DELETE FROM authors;
SET sql_safe_updates=1;
ALTER TABLE authors AUTO_INCREMENT = 1;

INSERT INTO authors (`author_name`,`author_type`) VALUE
('박상길', 'AUTHOR'), 
('정진호', 'PAINTER'),
('이남희', 'AUTHOR'),
('김덕진', 'AUTHOR'),
('강민철', 'AUTHOR'),
('프롬프트 크리에이터', 'AUTHOR'),
('루 샤오펑', 'AUTHOR'),
('김진호', 'TRANSLATOR'),
('서지영', 'AUTHOR'),
('설근민', 'AUTHOR'),
('엘튼 스톤맨', 'AUTHOR'),
('심효섭', 'TRANSLATOR'),
('최원영', 'AUTHOR'),
('주홍철', 'AUTHOR'),
('알렉스 쉬', 'AUTHOR'),
('이병준', 'TRANSLATOR'),
('천인국', 'AUTHOR'),
('공용해', 'AUTHOR'),
('하상호', 'AUTHOR'),
('구덕회', 'AUTHOR'),
('사이토 고키', 'AUTHOR'),
('개앞맵시', 'TRANSLATOR'),
('마크 시먼', 'AUTHOR'),
('김현규', 'TRANSLATOR'),
('반병현', 'AUTHOR'),
('시난 오즈데미르', 'AUTHOR'),
('신병훈', 'TRANSLATOR'),
('롤랜드 백하우스', 'AUTHOR'),
('김준원', 'TRANSLATOR'),
('윤교준', 'TRANSLATOR'),
('박해선', 'AUTHOR'),
('이수진', 'AUTHOR'),
('에단 부에노 데 메스키타', 'AUTHOR'),
('앤서니 파울러', 'AUTHOR'),
('임형준', 'TRANSLATOR'),
('우재남', 'AUTHOR'),
('벤 아우파스', 'AUTHOR'),
('이병욱', 'TRANSLATOR'),
('아오키 에이타', 'AUTHOR'),
('서수환', 'TRANSLATOR'),
('송석리', 'AUTHOR'),
('황수빈', 'AUTHOR'),
('이정윤', 'AUTHOR'),
('정유진', 'AUTHOR'),
('스티브 클라브닉', 'AUTHOR'),
('캐럴 니컬스', 'AUTHOR'),
('권지용', 'TRANSLATOR'),
('알렉스 쉬, 산 람', 'AUTHOR'),
('이병준', 'TRANSLATOR'),
('미치오 카쿠', 'AUTHOR'),
('박병철', 'TRANSLATOR'),
('김경동', 'AUTHOR'),
('고죠 마사유키', 'AUTHOR'),
('정현', 'TRANSLATOR'),
('박경록', 'AUTHOR'),
('마이크 코헨', 'AUTHOR'), 
('장정호', 'TRANSLATOR'),
('오렐리앙 제롱', 'AUTHOR'),
('리카이푸', 'AUTHOR'),
('천치우판', 'AUTHOR'),
('이현', 'TRANSLATOR'),
('고현민', 'AUTHOR'),
('길버트 스트랭', 'AUTHOR'),
('부산대학교 산업수학센터', 'TRANSLATOR'),
('최영규', 'AUTHOR'),
('정인근', 'AUTHOR'),
('마테우스 파쿠레', 'AUTHOR'), 
('신진수', 'TRANSLATOR'),
('가짜연구소 인과추론팀', 'TRANSLATOR'), 
('박지용', 'SUPERVISION'),
('알리 아미니안', 'AUTHOR'),
('알렉스 쉬', 'AUTHOR'), 
('최종일', 'TRANSLATOR'),
('권경열', 'AUTHOR'),
('찰스 펫졸드', 'AUTHOR'), 
('김현규', 'TRANSLATOR'),
('박상현', 'AUTHOR'),
('권원일', 'AUTHOR'), 
('김선준', 'AUTHOR'), 
('정기영', 'AUTHOR'),
('시바타 보요', 'AUTHOR'), 
('강민', 'TRANSLATOR'),
('Abraham Silberschatz', 'AUTHOR'),
('Peter Baer Galvin', 'AUTHOR'), 
('Greg Gagne', 'AUTHOR'), 
('박민규', 'TRANSLATOR'),
('최지호', 'AUTHOR'),
('김희성', 'AUTHOR'), 
('제레미 쿠비카', 'AUTHOR'), 
('오현석', 'TRANSLATOR'),
('로버트 C. 마틴', 'AUTHOR'), 
('이해영', 'TRANSLATOR'), 
('박재호', 'TRANSLATOR'),
('김준성', 'AUTHOR'), 
('브라이스 유', 'AUTHOR'), 
('안상준', 'AUTHOR'),
('브라이언 W. 커니핸', 'AUTHOR'), 
('하성창', 'TRANSLATOR'),
('김영우', 'AUTHOR'),
('백은빈', 'AUTHOR'),
('이성욱', 'AUTHOR'),
('권철민', 'AUTHOR'),
('조성호', 'AUTHOR'),
('이용태', 'AUTHOR'),
('한국정보통신기술협회', 'AUTHOR'),
('이현열', 'AUTHOR'),
('최범균', 'AUTHOR'),
('다니엘 드레셔', 'AUTHOR'), 
('이병욱', 'TRANSLATOR'),
('김철수', 'AUTHOR'),
('Behrouz A. Forouzan', 'AUTHOR'), 
('이재광', 'TRANSLATOR'), 
('김중규', 'TRANSLATOR'), 
('이경현', 'TRANSLATOR'),
('홍충선', 'TRANSLATOR'),
('오일석', 'AUTHOR'),
('조성준', 'AUTHOR'), 
('조재희', 'AUTHOR'), 
('김성범', 'AUTHOR'), 
('이성임', 'AUTHOR'), 
('조성배', 'AUTHOR'), 
('이영훈', 'AUTHOR'),
('그웬 샤피라', 'AUTHOR'), 
('토드 팔리노', 'AUTHOR'), 
('라지니 시바람', 'AUTHOR'), 
('크리트 페티', 'AUTHOR'), 
('이동진', 'TRANSLATOR'),
('헤더림(임혜린)', 'AUTHOR'), 
('백승호', 'AUTHOR'),
('다니엘 첸', 'AUTHOR'), 
('시진', 'TRANSLATOR'),
('Robert W. Sebesta', 'AUTHOR'),
('하상호', 'TRANSLATOR'),
('유원희', 'TRANSLATOR'),
('김혜진', 'AUTHOR'), 
('왕진영', 'AUTHOR'),
('DMeloper', 'AUTHOR'),
('나동빈', 'AUTHOR'),
('임석구', 'AUTHOR'), 
('홍경호', 'AUTHOR'),
('존 맥코믹', 'AUTHOR'), 
('민병교', 'TRANSLATOR'),
('김창준', 'AUTHOR'),
('김연희', 'AUTHOR'),
('마티 케이건', 'AUTHOR'), 
('황진수', 'TRANSLATOR'),
('노버트 위너', 'AUTHOR'), 
('김재영', 'TRANSLATOR'),
('이규남', 'AUTHOR'), 
('조우진', 'AUTHOR'), 
('김동민', 'AUTHOR'),
('김치수', 'AUTHOR'),
('이지영', 'AUTHOR'),
('진강훈', 'AUTHOR'),
('조태호', 'AUTHOR'),
('데이비드 포스터', 'AUTHOR'), 
('박해선', 'TRANSLATOR'),
('김대수', 'AUTHOR'), 
('이기창', 'AUTHOR'),
('조훈', 'AUTHOR'), 
('심근우', 'AUTHOR'), 
('문성주', 'AUTHOR'),
('고경희', 'AUTHOR'), 
('이고잉', 'AUTHOR'),
('나가노 히로유키', 'AUTHOR'), 
('서재원', 'TRANSLATOR');
